name: Build and Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          apt install ffmpeg -y

      - name: Test
        run: |
          python main.py "Unholy Matrimony Giveon"
          stat "Giveon_-_Unholy_Matrimony_Official_Lyric_Video-clipped.mp3"
